name: 'release app'

on:
    push:
        branches:
            - 'main'

env:
    GIT_AUTHOR_NAME: 'jenjonesarnesen'
    GIT_AUTHOR_EMAIL: 'jennifer@dhis2.org'
    GIT_COMMITTER_NAME: 'jenjonesarnesen'
    GIT_COMMITTER_EMAIL: 'jennifer@dhis2.org'
    GH_TOKEN: ${{secrets.GH_TOKEN}}
    APPHUB_TOKEN: ${{secrets.APPHUB_TOKEN}}
    CI: true

jobs:
    build:
        if: ${{ !contains(github.event.head_commit.message, '[skip release]') }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn d2-app-scripts build

            - uses: actions/upload-artifact@v3
              with:
                  name: app-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    
    prepare-release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ env.GH_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - uses: actions/download-artifact@v3
              with:
                  name: app-build

            - name: Install
              run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-apphub: false
                  publish-github: false
                  github-token: ${{ env.GH_TOKEN }}
                  apphub-token: ${{ env.APPHUB_TOKEN }}
