name: 'release'

on:
    push:
        branches:
            - 'main'

env:
    GIT_AUTHOR_NAME: 'jenjonesarnesen'
    GIT_AUTHOR_EMAIL: 'jennifer@dhis2.org'
    GIT_COMMITTER_NAME: 'jenjonesarnesen'
    GIT_COMMITTER_EMAIL: 'jennifer@dhis2.org'
    GH_TOKEN: ${{secrets.GH_TOKEN}}
    APPHUB_TOKEN: ${{secrets.APPHUB_TOKEN}}
    CI: true

jobs:
    release:
        if: ${{ !contains(github.event.head_commit.message, '[skip release]') }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ env.GH_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Run Semantic Release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx -p semantic-release@20.0.0 semantic-release
            