name: 'release'

on:
    push:
        branches:
            - 'main'

env:
    GIT_AUTHOR_NAME: 'jenjonesarnesen'
    GIT_AUTHOR_EMAIL: 'jennifer@dhis2.org'
    GIT_COMMITTER_NAME: 'jenjonesarnesen'
    GIT_COMMITTER_EMAIL: 'jennifer@dhis2.org'
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    D2_APP_HUB_TOKEN: ${{secrets.DHIS2_BOT_APPHUB_TOKEN}}
    CI: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Run Semantic Release
              run: npx -p semantic-release@20.0.0 semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Set build-exists output
              id: check_build
              run: |
                  if ls build/bundle/maps-*.zip 1> /dev/null 2>&1; then
                      echo "::set-output name=build_exists::true"
                  else
                      echo "::set-output name=build_exists::false"
                  fi

            - name: Publish to AppHub
              if: steps.check_build.outputs.build_exists == 'true'
              run: yarn run d2-app-scripts publish
            